# Config file for automatic testing at travis-ci.org
language: python

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
      choco install miniconda3 --params="'/AddToPath:1'";
      export PATH="/c/tools/miniconda3/scripts:/c/tools/miniconda3/:/c/Program Files/Git/miniconda3/bin/:$PATH";
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda no
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then conda update -q conda; fi

install:
  - conda env update -n root -f environment.yml

script:
  - black --check . --line-length 120
  - python setup.py install
  - pytest -v --color=yes

notifications:
  email:
    on_success: never
    on_failure: always
