# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: bioptim
channels:
- conda-forge
dependencies:
- python >=3.10
- biorbd >=1.12.0
- matplotlib
- pyqt
- pyqtgraph
- python-graphviz
- numpy <2.4