# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: bioptim
channels:
- conda-forge
- default
dependencies:
- biorbd >=1.8.3
- bioviz
- scipy
- numpy
- packaging
- python-graphviz
- pyqtgraph
- python >=3.10
